/**
 * Built-in home heading banners for the professional shell.
 * Nature stays. Age, family and people packs are not offered.
 *
 * Drop source art in assets/home-banners/natur/
 * then run `node scripts/generate-responsive-images.mjs --roots assets/home-banners`
 * and add a row with `.medium.jpg` (display) + `.thumb.jpg` (picker).
 */

export const HOME_BANNER_PACKS = ['natur'];

export const HOME_BANNER_GROUPS = [
  { id: 'natur', label: 'Natur', hint: 'Fjell, fjord og lys' },
  { id: 'eget', label: 'Eget', hint: 'Last opp selv' },
];

export const HOME_BANNERS = [
  {
    id: 'gutt-smaabarn-klosser',
    pack: 'gutt',
    group: 'smaabarn',
    label: 'Klosser på teppet',
    description: 'Lekestue med klosser — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/gutt/smaabarn-klosser.medium.jpg'),
    thumb: require('../assets/home-banners/gutt/smaabarn-klosser.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'jente-smaabarn-klosser',
    pack: 'jente',
    group: 'smaabarn',
    label: 'Klosser i lekerommet',
    description: 'Småbarn med klosser i lekerommet — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/jente/jente-smaabarn-klosser.medium.jpg'),
    thumb: require('../assets/home-banners/jente/jente-smaabarn-klosser.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'jente-smaabarn-sapa',
    pack: 'jente',
    group: 'smaabarn',
    label: 'Såpebobler',
    description: 'Småbarn som jager såpebobler — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/jente/jente-smaabarn-sapa.medium.jpg'),
    thumb: require('../assets/home-banners/jente/jente-smaabarn-sapa.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'noytralt-smaabarn-barnerom',
    pack: 'noytralt',
    group: 'smaabarn',
    label: 'Rolig barnerom',
    description: 'Tomt lekerom med klosser og kosedyr — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/noytralt/noytralt-smaabarn-barnerom.medium.jpg'),
    thumb: require('../assets/home-banners/noytralt/noytralt-smaabarn-barnerom.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'noytralt-smaabarn-lekeplass',
    pack: 'noytralt',
    group: 'smaabarn',
    label: 'Lekeplass',
    description: 'Lekeplass med såpebobler — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/noytralt/noytralt-smaabarn-lekeplass.medium.jpg'),
    thumb: require('../assets/home-banners/noytralt/noytralt-smaabarn-lekeplass.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'gutt-barn-sparkesykkel',
    pack: 'gutt',
    group: 'barn',
    label: 'Sparkesykkel',
    description: 'Utelek ved sjøen — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/gutt/barn-sparkesykkel.medium.jpg'),
    thumb: require('../assets/home-banners/gutt/barn-sparkesykkel.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'jente-barn-piknik',
    pack: 'jente',
    group: 'barn',
    label: 'Piknik ved vannet',
    description: 'Piknik, rød hytte og sykkel ved vannet — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/jente/jente-barn-piknik.medium.jpg'),
    thumb: require('../assets/home-banners/jente/jente-barn-piknik.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'jente-barn-sykkel',
    pack: 'jente',
    group: 'barn',
    label: 'På sykkel ved vannet',
    description: 'Sykkel langs alpeinnsjøen — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/jente/jente-barn-sykkel.medium.jpg'),
    thumb: require('../assets/home-banners/jente/jente-barn-sykkel.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'jente-barn-fotball',
    pack: 'jente',
    group: 'barn',
    label: 'Fotball på gresset',
    description: 'Fotball på gresset — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/jente/jente-barn-fotball.medium.jpg'),
    thumb: require('../assets/home-banners/jente/jente-barn-fotball.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'gutt-barn-tur',
    pack: 'gutt',
    group: 'barn',
    label: 'På tur',
    description: 'Utsikt, kikkert og hund — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/gutt/barn-tur.medium.jpg'),
    thumb: require('../assets/home-banners/gutt/barn-tur.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'jente-barn-tur',
    pack: 'jente',
    group: 'barn',
    label: 'På tur i skogen',
    description: 'Tur i skogen med lilla sekk — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/jente/jente-barn-tur.medium.jpg'),
    thumb: require('../assets/home-banners/jente/jente-barn-tur.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'jente-barn-strand',
    pack: 'jente',
    group: 'barn',
    label: 'Skjell på stranden',
    description: 'Skjell og sand ved havet — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/jente/jente-barn-strand.medium.jpg'),
    thumb: require('../assets/home-banners/jente/jente-barn-strand.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'noytralt-barn-tur',
    pack: 'noytralt',
    group: 'barn',
    label: 'På tur',
    description: 'Tursekk langs sti mot vann og fjell — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/noytralt/noytralt-barn-tur.medium.jpg'),
    thumb: require('../assets/home-banners/noytralt/noytralt-barn-tur.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'noytralt-barn-sykkel',
    pack: 'noytralt',
    group: 'barn',
    label: 'Sykkel ved fjorden',
    description: 'Sykkelhjelm ved fjorden — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/noytralt/noytralt-barn-sykkel.medium.jpg'),
    thumb: require('../assets/home-banners/noytralt/noytralt-barn-sykkel.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'noytralt-barn-fotball',
    pack: 'noytralt',
    group: 'barn',
    label: 'Fotballbane',
    description: 'Fotball på banen — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/noytralt/noytralt-barn-fotball.medium.jpg'),
    thumb: require('../assets/home-banners/noytralt/noytralt-barn-fotball.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'noytralt-barn-piknik',
    pack: 'noytralt',
    group: 'barn',
    label: 'Piknik',
    description: 'Piknikteppe ved vannet — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/noytralt/noytralt-barn-piknik.medium.jpg'),
    thumb: require('../assets/home-banners/noytralt/noytralt-barn-piknik.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'gutt-ungdom-skole',
    pack: 'gutt',
    group: 'ungdom',
    label: 'Etter skolen',
    description: 'Fotball og pause etter skolen — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/gutt/ungdom-skole.medium.jpg'),
    thumb: require('../assets/home-banners/gutt/ungdom-skole.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'jente-ungdom-kyststi',
    pack: 'jente',
    group: 'ungdom',
    label: 'Kyststi i kveldssol',
    description: 'Tur langs kyststien i kveldssol — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/jente/jente-ungdom-kyststi.medium.jpg'),
    thumb: require('../assets/home-banners/jente/jente-ungdom-kyststi.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'gutt-ungdom-laptop',
    pack: 'gutt',
    group: 'ungdom',
    label: 'Egen tid',
    description: 'Laptop ved vannet. Svart bakgrunn som fader inn i siden.',
    source: require('../assets/home-banners/gutt/ungdom-laptop.medium.jpg'),
    thumb: require('../assets/home-banners/gutt/ungdom-laptop.thumb.jpg'),
    fit: 'contain',
    align: 'center',
    cutout: true,
    fullscreen: true,
  },
  {
    id: 'jente-ungdom-vindu',
    pack: 'jente',
    group: 'ungdom',
    label: 'Kveld ved vinduet',
    description: 'Lesestund ved vinduet mot fjorden — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/jente/jente-ungdom-vindu.medium.jpg'),
    thumb: require('../assets/home-banners/jente/jente-ungdom-vindu.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'gutt-ungdom-kveld',
    pack: 'gutt',
    group: 'ungdom',
    label: 'Kveldslys',
    description: 'Solnedgang på berget. Svart bakgrunn som fader inn i siden.',
    source: require('../assets/home-banners/gutt/ungdom-kveld.medium.jpg'),
    thumb: require('../assets/home-banners/gutt/ungdom-kveld.thumb.jpg'),
    fit: 'contain',
    align: 'center',
    cutout: true,
    fullscreen: true,
  },
  {
    id: 'jente-ungdom-brygge',
    pack: 'jente',
    group: 'ungdom',
    label: 'På brygga',
    description: 'På brygga ved fjellvannet — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/jente/jente-ungdom-brygge.medium.jpg'),
    thumb: require('../assets/home-banners/jente/jente-ungdom-brygge.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'noytralt-ungdom-stjerner',
    pack: 'noytralt',
    group: 'ungdom',
    label: 'Stjernehimmel',
    description: 'Teleskop under stjernehimmelen ved vannet — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/noytralt/noytralt-ungdom-stjerner.medium.jpg'),
    thumb: require('../assets/home-banners/noytralt/noytralt-ungdom-stjerner.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'noytralt-ungdom-skate',
    pack: 'noytralt',
    group: 'ungdom',
    label: 'Skateboard i kveldssol',
    description: 'Skateboard mot kysten i kveldssol — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/noytralt/noytralt-ungdom-skate.medium.jpg'),
    thumb: require('../assets/home-banners/noytralt/noytralt-ungdom-skate.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'noytralt-ungdom-tegnebord',
    pack: 'noytralt',
    group: 'ungdom',
    label: 'Tegnebord',
    description: 'Tegnebord mot fjordlandsbyen — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/noytralt/noytralt-ungdom-tegnebord.medium.jpg'),
    thumb: require('../assets/home-banners/noytralt/noytralt-ungdom-tegnebord.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'noytralt-ungdom-pult',
    pack: 'noytralt',
    group: 'ungdom',
    label: 'Pult mot fjorden',
    description: 'Pult og journal mot fjorden i solnedgang — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/noytralt/noytralt-ungdom-pult.medium.jpg'),
    thumb: require('../assets/home-banners/noytralt/noytralt-ungdom-pult.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'voksen-middag-plan',
    pack: 'voksen',
    group: 'voksen',
    label: 'Middagsplan',
    description: 'Handleposer, ukesmeny og et øyeblikks ro — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/voksen/middag-plan.medium.jpg'),
    thumb: require('../assets/home-banners/voksen/middag-plan.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'voksen-hjemmekontor',
    pack: 'voksen',
    group: 'voksen',
    label: 'Hjemmekontor',
    description: 'Pult, kaffe og utsikt — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/voksen/hjemmekontor.medium.jpg'),
    thumb: require('../assets/home-banners/voksen/hjemmekontor.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'voksen-delt-omsorg',
    pack: 'voksen',
    group: 'voksen',
    label: 'To hjem',
    description: 'Kalender, bag og veien mellom husene — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/voksen/delt-omsorg.medium.jpg'),
    thumb: require('../assets/home-banners/voksen/delt-omsorg.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'voksen-familiechat',
    pack: 'voksen',
    group: 'voksen',
    label: 'Kveldsmelding',
    description: 'Sofa og en stille prat med familien — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/voksen/familiechat.medium.jpg'),
    thumb: require('../assets/home-banners/voksen/familiechat.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'voksen-kveld-plan',
    pack: 'voksen',
    group: 'voksen',
    label: 'Kveldsplan',
    description: 'Notatbok og nettbrett når huset har lagt seg — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/voksen/kveld-plan.medium.jpg'),
    thumb: require('../assets/home-banners/voksen/kveld-plan.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'voksen-morgen-plan',
    pack: 'voksen',
    group: 'voksen',
    label: 'Morgen ved bordet',
    description: 'Kaffe, ukeplan og soloppgang over fjorden — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/voksen/morgen-plan.medium.jpg'),
    thumb: require('../assets/home-banners/voksen/morgen-plan.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'natur-fjelltopp',
    pack: 'natur',
    group: 'natur',
    label: 'På toppen',
    description: 'Soloppgang over fjell og vann — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/natur/fjelltopp.medium.jpg'),
    thumb: require('../assets/home-banners/natur/fjelltopp.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'natur-hytte-regn',
    pack: 'natur',
    group: 'natur',
    label: 'Regn og peis',
    description: 'Hytte, peis og utsikt gjennom regnet — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/natur/hytte-regn.medium.jpg'),
    thumb: require('../assets/home-banners/natur/hytte-regn.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'natur-terrasse',
    pack: 'natur',
    group: 'natur',
    label: 'Kaffe på terrassen',
    description: 'Morgenlys over innsjø og fjell — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/natur/terrasse.medium.jpg'),
    thumb: require('../assets/home-banners/natur/terrasse.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'natur-kyststi',
    pack: 'natur',
    group: 'natur',
    label: 'Kyststi',
    description: 'Sti langs havet i kveldslys — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/natur/kyststi.medium.jpg'),
    thumb: require('../assets/home-banners/natur/kyststi.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'natur-skogsti',
    pack: 'natur',
    group: 'natur',
    label: 'Skogsti',
    description: 'Mose, benk og sti mot vannet — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/natur/skogsti.medium.jpg'),
    thumb: require('../assets/home-banners/natur/skogsti.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'natur-utsikt',
    pack: 'natur',
    group: 'natur',
    label: 'Utsikt over øyer',
    description: 'Ro på berget når solen går ned — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/natur/utsikt.medium.jpg'),
    thumb: require('../assets/home-banners/natur/utsikt.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'natur-brygge',
    pack: 'natur',
    group: 'natur',
    label: 'Brygge i tåke',
    description: 'Fjord og soloppgang fra brygga — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/natur/brygge.medium.jpg'),
    thumb: require('../assets/home-banners/natur/brygge.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'natur-nordlys',
    pack: 'natur',
    group: 'natur',
    label: 'Nordlys',
    description: 'Grønt lys over fjord og fjell — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/natur/nordlys.medium.jpg'),
    thumb: require('../assets/home-banners/natur/nordlys.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'natur-skjergard',
    pack: 'natur',
    group: 'natur',
    label: 'Skjærgård',
    description: 'Badestige, båt og rød hytte — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/natur/skjergard.medium.jpg'),
    thumb: require('../assets/home-banners/natur/skjergard.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'natur-badestamp',
    pack: 'natur',
    group: 'natur',
    label: 'Badestamp',
    description: 'Kveldskar og utsikt over fjorden — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/natur/badestamp.medium.jpg'),
    thumb: require('../assets/home-banners/natur/badestamp.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'natur-innsjo-hytte-morgen',
    pack: 'natur',
    group: 'natur',
    label: 'Innsjø om morgenen',
    description: 'Hytte, furu og stille vann i soloppgang — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/natur/innsjo-hytte-morgen.medium.jpg'),
    thumb: require('../assets/home-banners/natur/innsjo-hytte-morgen.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'natur-fjordterrasse-kveld',
    pack: 'natur',
    group: 'natur',
    label: 'Kveld på terrassen',
    description: 'Solnedgang over fjord og fjell — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/natur/fjordterrasse-kveld.medium.jpg'),
    thumb: require('../assets/home-banners/natur/fjordterrasse-kveld.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'natur-fjellbrygge-morgen',
    pack: 'natur',
    group: 'natur',
    label: 'Brygge i fjellvann',
    description: 'Soloppgang fra brygga — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/natur/fjellbrygge-morgen.medium.jpg'),
    thumb: require('../assets/home-banners/natur/fjellbrygge-morgen.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'natur-kyst-solnedgang',
    pack: 'natur',
    group: 'natur',
    label: 'Kyst i solnedgang',
    description: 'Klippekyst og solnedgang over havet — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/natur/kyst-solnedgang.medium.jpg'),
    thumb: require('../assets/home-banners/natur/kyst-solnedgang.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'natur-eng-tåke',
    pack: 'natur',
    group: 'natur',
    label: 'Eng i tåke',
    description: 'Tåke og soloppgang over gressenga — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/natur/eng-take.medium.jpg'),
    thumb: require('../assets/home-banners/natur/eng-take.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'natur-skogsti-mose',
    pack: 'natur',
    group: 'natur',
    label: 'Skogsti med mose',
    description: 'Mosegrodd sti gjennom skogen — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/natur/skogsti-mose.medium.jpg'),
    thumb: require('../assets/home-banners/natur/skogsti-mose.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'natur-alpeinnsjo',
    pack: 'natur',
    group: 'natur',
    label: 'Alpeinnsjø',
    description: 'Fjellvann med speiling av toppene — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/natur/alpeinnsjo.medium.jpg'),
    thumb: require('../assets/home-banners/natur/alpeinnsjo.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'natur-fjord-soloppgang',
    pack: 'natur',
    group: 'natur',
    label: 'Fjord i soloppgang',
    description: 'Soloppgang over fjorden — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/natur/fjord-soloppgang.medium.jpg'),
    thumb: require('../assets/home-banners/natur/fjord-soloppgang.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'natur-dalføre',
    pack: 'natur',
    group: 'natur',
    label: 'Dalføre',
    description: 'Elv gjennom dalføret mellom fjellene — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/natur/dalfore.medium.jpg'),
    thumb: require('../assets/home-banners/natur/dalfore.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'natur-måne-innsjo',
    pack: 'natur',
    group: 'natur',
    label: 'Måne over vann',
    description: 'Måne over innsjø og siv — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/natur/mane-innsjo.medium.jpg'),
    thumb: require('../assets/home-banners/natur/mane-innsjo.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'natur-foss',
    pack: 'natur',
    group: 'natur',
    label: 'Foss',
    description: 'Foss i skogen — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/natur/foss.medium.jpg'),
    thumb: require('../assets/home-banners/natur/foss.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'natur-lilla-kveld',
    pack: 'natur',
    group: 'natur',
    label: 'Lilla kveld',
    description: 'Lilla og rosa kveldslys over vannet — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/natur/lilla-kveld.medium.jpg'),
    thumb: require('../assets/home-banners/natur/lilla-kveld.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
  {
    id: 'natur-sandstrand',
    pack: 'natur',
    group: 'natur',
    label: 'Sandstrand',
    description: 'Sanddyner mot havet — heldekkende bakgrunn på mobil.',
    source: require('../assets/home-banners/natur/sandstrand.medium.jpg'),
    thumb: require('../assets/home-banners/natur/sandstrand.thumb.jpg'),
    fit: 'cover',
    align: 'center',
    fullscreen: true,
  },
];

export const DEFAULT_HOME_BANNER_ID = 'natur-innsjo-hytte-morgen';
export const DEFAULT_CHILD_HOME_BANNER_ID = 'noytralt-smaabarn-barnerom';
export const CUSTOM_BANNER_ID = 'custom';

function isOfferedBanner(banner) {
  return banner?.group === 'natur' && banner?.pack === 'natur';
}

export function bannersInGroup(groupId) {
  if (groupId !== 'natur') return [];
  return HOME_BANNERS.filter(isOfferedBanner);
}

export function getHomeBanner(id) {
  if (!id || id === CUSTOM_BANNER_ID) return null;
  const hit = HOME_BANNERS.find((b) => b.id === id);
  if (isOfferedBanner(hit)) return hit;
  return HOME_BANNERS.find((b) => b.id === DEFAULT_HOME_BANNER_ID)
    || HOME_BANNERS.find(isOfferedBanner)
    || null;
}

export function isValidHomeBannerId(id) {
  if (id === CUSTOM_BANNER_ID) return true;
  return isOfferedBanner(HOME_BANNERS.find((b) => b.id === id));
}

export function recommendedBannerGroupForAge() {
  return 'natur';
}

export function homeSceneTitle(dayPart) {
  if (dayPart === 'evening') return 'En fin kveld!';
  if (dayPart === 'afternoon') return 'En fin ettermiddag!';
  return 'En fin dag!';
}

export const HOME_SCENE_SUBTITLE = 'Oversikt for jobb og næringsliv.';

export function homeSceneTagline(dayPart) {
  if (dayPart === 'evening') return 'Roligere dager skaper sterkere dager';
  if (dayPart === 'afternoon') return 'En roligere ettermiddag gir mer overskudd';
  return 'En roligere morgen gir en bedre dag';
}

export const HOME_FOOTER_LINE = 'Jobb, nettverk og oversikt';
